Revert "Bump com.gradle:gradle-enterprise-gradle-plugin from 3.16 to 3.16.1"
This reverts commit 1c966eb41444fbbbb2f26bdbd65ea5939cfb1919 due to the
following error.

> Task :junit-platform-runner:eclipseClasspath
Could not resolve: junit:junit:{require [4.12,); prefer 4.13.2}
Internal error in Gradle Enterprise Gradle plugin: finished notification
com.gradle.scan.plugin.BuildScanException: Internal error in Gradle Enterprise Gradle plugin: finished notification
        at com.gradle.scan.plugin.BuildScanException.a(SourceFile:25)
        at com.gradle.scan.plugin.internal.operations.d.a(SourceFile:116)
        at com.gradle.scan.plugin.internal.operations.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
        at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /Users/<username>/.gradle/.tmp/gradle304773911965233218.bin offset 778 exists? true