Fix build due to JfrUnit's support for Spock 2
JfrUnit now supports Spock 2.

Specifically, @JfrEventTest is annotated with @ExtensionAnnotation
which resulted in the following build error.

> Task :platform-tests:compileTestJava
/.../jfrunit-main-SNAPSHOT.jar(/dev/morling/jfrunit/JfrEventTest.class):
  warning: Cannot find annotation method 'value()' in type 'ExtensionAnnotation':
  class file for org.spockframework.runtime.extension.ExtensionAnnotation not found
error: warnings found and -Werror specified
1 error
1 warning
> Task :platform-tests:compileTestJava FAILED

This commit allows the build to proceed by adding a testCompileOnly
dependency on Spock 2 in the platform-tests project.