Introduce circular dependency...
org.gradle.api.CircularReferenceException: Circular dependency between the following tasks:
:junit-jupiter-params:classes
\--- :junit-jupiter-params:compileModuleJava
     \--- :junit-jupiter-params:compileModuleKotlin
          \--- :junit-jupiter-params:classes (*)