Avoid NullPointerExceptions in console output in tests
Prior to this commit, the following types of NullPointerExceptions were
overlooked in the console output.

java.lang.NullPointerException: Cannot invoke "org.junit.platform.console.tasks.ConsoleTestExecutor.execute(java.io.PrintWriter, java.util.Optional)" because the return value of "org.junit.platform.console.tasks.ConsoleTestExecutor$Factory.create(org.junit.platform.console.options.TestDiscoveryOptions, org.junit.platform.console.options.TestConsoleOutputOptions)" is null

Although the NullPointerExceptions did not cause the tests to fail,
this commit updates the tests to avoid them anyway.

(cherry picked from commit bc862e01288a8392992c32c03dd8f25cb1b6023f)