Use @JvmField instead of @JvmStatic in Kotlin / @RegisterExtension
The documentation says:

>The Kotlin programming language does not have the concept of a static field. However, the compiler can be instructed to generate a private static field using the @JvmStatic annotation in Kotlin. If you want the Kotlin compiler to generate a public static field, you can use the @JvmField annotation instead.

But the example shows the use of `@JvmStatic`, which is not working with, e.g. WireMock:

```kotlin
companion object {
    @RegisterExtension
    @JvmStatic
    val wireMock = WireMockExtension.newInstance().options(wireMockConfig().dynamicPort()).build()
}
```

Gives

```
org.junit.platform.commons.PreconditionViolationException: Failed to register extension via @RegisterExtension field [private static final com.github.tomakehurst.wiremock.junit5.WireMockExtension a.b.c.ClientTest.wireMock]: field must not be private.
```